{% set python_min = "3.9" %}
{% set version = "0.13.0" %}

package:
  name: ttkwidgets
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/ttkwidgets/ttkwidgets-{{ version }}.tar.gz
  sha256: 9b1d69dffebef1820ee46b244469913d1911a563a15bb9b0823c71c950daead7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - pip
  run:
    - python >={{ python_min }}
    - pillow

test:
  imports:
    - ttkwidgets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://www.github.com/RedFantom/ttkwidgets
  summary: A collection of widgets for Tkinter's ttk extensions by various authors
  license: GPL-3.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
