#!/usr/bin/env python3
"""Compare repeat targeting: fig7_pred_conf vs fig7_original .not.mat files.

Same as compare_repeat_targeting.py but reads predicted labels from
fig7_pred_conf/ (generated by run_inference_fig7_conf.py with CONF_THRESHOLD=0.7).

Usage:
    python3 compare_repeat_targeting_conf.py
"""

from pathlib import Path
from scipy.io import loadmat
import numpy as np

ORIG_DIR = Path("/Users/riekers/.moove/rec_data/gy07bu07/fig7_original/250902")
PRED_DIR = Path("/Users/riekers/.moove/rec_data/gy07bu07/fig7_pred_conf/250902")

CHUNK_SIZE   = 64
SAMPLE_RATE  = 44100
COLLAR_MS    = 20
COLLAR_FRAMES = round(COLLAR_MS * SAMPLE_RATE / (CHUNK_SIZE * 1000))

TARGET_FIDS = [
    "161452", "161219", "143043", "142805",
    "133448", "132156", "131843", "124534",
    "120715", "115940", "115923", "115531",
]


def load_nm(path):
    nm = loadmat(str(path))
    onsets  = nm["onsets"].flatten().tolist()
    offsets = nm["offsets"].flatten().tolist()
    labels  = list(str(nm["labels"].flat[0]))[:len(onsets)]
    return onsets, offsets, labels


def ms_to_frames(ms):
    return int(ms * SAMPLE_RATE / (1000 * CHUNK_SIZE))


def runs_of_a(onsets, offsets, labels):
    """Find runs of >=4 consecutive 'a', return trigger info per run."""
    triggers = []
    i = 0
    while i < len(labels):
        if labels[i] == 'a':
            rs = i
            while i < len(labels) and labels[i] == 'a':
                i += 1
            run_len = i - rs
            if run_len >= 4:
                triggers.append({
                    "trigger_onset_ms": onsets[rs + 3],
                    "run_start_f": ms_to_frames(onsets[rs]),
                    "run_end_f":   ms_to_frames(offsets[i - 1]),
                    "run_len":     run_len,
                })
        else:
            i += 1
    return triggers


def analyze(fid):
    wav_glob = list(ORIG_DIR.glob(f"gy07bu07_250902_{fid}*.wav"))
    if not wav_glob:
        return None
    wav_name = wav_glob[0].name

    orig_on, orig_off, orig_lbl = load_nm(ORIG_DIR / (wav_name + ".not.mat"))
    pred_notmat = PRED_DIR / (wav_name + ".not.mat")
    if not pred_notmat.exists():
        print(f"  MISSING pred notmat: {fid} ({pred_notmat})")
        return None
    pred_on, pred_off, pred_lbl = load_nm(pred_notmat)

    true_trigs = runs_of_a(orig_on, orig_off, orig_lbl)
    pred_trigs = runs_of_a(pred_on, pred_off, pred_lbl)

    matched_true = set()
    matched_run_ranges = []
    tp = fp = 0
    issues = []

    for pt in pred_trigs:
        pf = ms_to_frames(pt["trigger_onset_ms"])
        # Typ3: pred trigger inside an already-matched true run → exclude
        if any(rs <= pf <= re for rs, re in matched_run_ranges):
            continue
        hit = False
        for ti, tt in enumerate(true_trigs):
            if ti in matched_true:
                continue
            if abs(pf - ms_to_frames(tt["trigger_onset_ms"])) <= COLLAR_FRAMES:
                matched_true.add(ti)
                matched_run_ranges.append((tt["run_start_f"], tt["run_end_f"]))
                tp += 1
                hit = True
                break
        if not hit:
            best_lbl, best_dist = "?", 1e9
            for k, (on, off) in enumerate(zip(orig_on, orig_off)):
                on_f = ms_to_frames(on)
                off_f = ms_to_frames(off)
                d = 0 if on_f <= pf <= off_f else min(abs(pf - on_f), abs(pf - off_f))
                if d < best_dist:
                    best_dist = d
                    best_lbl = orig_lbl[k] if k < len(orig_lbl) else "?"
            fp += 1
            issues.append(f"FP {pt['trigger_onset_ms']/1000:.2f}s "
                           f"(pred {pt['run_len']}×a, nearest_true={best_lbl})")

    fn = len(true_trigs) - len(matched_true)
    for ti, tt in enumerate(true_trigs):
        if ti not in matched_true:
            tf = ms_to_frames(tt["trigger_onset_ms"])
            near = []
            for k, on in enumerate(pred_on):
                on_f = ms_to_frames(on)
                if abs(on_f - tf) <= COLLAR_FRAMES * 3:
                    lbl = pred_lbl[k] if k < len(pred_lbl) else "?"
                    near.append(f"{lbl}({on_f - tf:+d}f)")
            near_str = ", ".join(near[:4]) if near else "—"
            issues.append(f"FN {tt['trigger_onset_ms']/1000:.2f}s "
                           f"(true {tt['run_len']}×a, near=[{near_str}])")

    return {
        "n_true": len(true_trigs),
        "n_pred": len(pred_trigs),
        "tp": tp, "fp": fp, "fn": fn,
        "issues": issues,
    }


def main():
    rows = []
    totals = {"n_true": 0, "n_pred": 0, "tp": 0, "fp": 0, "fn": 0}

    for fid in TARGET_FIDS:
        r = analyze(fid)
        if r is None:
            print(f"MISSING: {fid}")
            continue
        rows.append((fid, r))
        for k in totals:
            totals[k] += r[k]

    # Header
    print(f"{'File':<20} {'n_true':>6} {'n_pred':>6} {'TP':>4} {'FP':>4} {'FN':>4}  {'hit':>5}  Details")
    print("─" * 125)

    for fid, r in rows:
        hit = f"{r['tp']}/{r['n_true']}" if r["n_true"] else "—"
        detail = "  ·  ".join(r["issues"]) if r["issues"] else "✓"
        print(f"{fid:<20} {r['n_true']:>6} {r['n_pred']:>6} {r['tp']:>4} {r['fp']:>4} {r['fn']:>4}  {hit:>5}  {detail}")

    print("─" * 125)
    tp = totals["tp"]; fp = totals["fp"]; fn = totals["fn"]
    n = totals["n_true"]
    prec = tp / (tp + fp) if tp + fp else 0
    rec  = tp / (tp + fn) if tp + fn else 0
    f1   = 2 * prec * rec / (prec + rec) if prec + rec else 0
    print(f"{'TOTAL':<20} {n:>6} {totals['n_pred']:>6} {tp:>4} {fp:>4} {fn:>4}  {tp}/{n}")
    print(f"Precision={prec:.3f}  Recall={rec:.3f}  F1={f1:.3f}  (collar={COLLAR_MS}ms, Typ3 excluded)")


if __name__ == "__main__":
    main()
